### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by irtiza-matech** [ilmedova/chattle#5]
Hi, @ilmedova @aishahzbr 
This package is not working on laravel 10. I tried a lot. Every time i got the error that it requires laravel 9. 

Problem 1
    - Root composer.json requires ilmedova/chattle ^1.0 -> satisfiable by ilmedova/chattle[v1.0.0].
    - ilmedova/chattle v1.0.0 requires laravel/framework ^9.0 -> found laravel/framework[v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^10.10)
    - 
Can you please make it work with laravel 10. It will be good for many people. 

Thanks

**Comment by ilmedova** [comment]
Hello @irtiza-matech
Updated to laravel 10, please read the instructions carefully while installing the package as I updated the documentation too

**Comment by irtiza-matech** [comment]
I've installed it successfully.
Thank you so much, @ilmedova
